title: "awilkes.org"
description: "Thoughts, notes, and experiments."
author: "Alastair Wilkes"

# Use GitHubâ€™s default supported theme
# theme: minima

# If your site lives at https://your-username.github.io
url: "https://awilkes.org"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional nice-to-haves
permalink: /:title/
